use image_slim_core::error::{AppError, ErrorCode};
use image_slim_core::model::{
    AppCapabilities, BatchRequest, BatchStartResult, BatchStartStatus, BatchSummary,
    CompressionPreset, FormatCapability, ImageFormat, InputItem, InputLimits, ItemProgress,
    MetadataPolicy, OutputMode, PreviewRequest, PreviewResult, ScanEvent, ScanRequest, TaskStatus,
};
use std::env;
use std::fs;
use std::path::PathBuf;
use ts_rs::{Config, TS};

fn main() {
    let mut arguments = env::args().skip(1);
    let output = PathBuf::from(arguments.next().expect("missing output path"));
    let check = arguments.any(|argument| argument == "--check");
    let config = Config::default();
    let declarations = [
        ErrorCode::decl(&config),
        AppError::decl(&config),
        ImageFormat::decl(&config),
        CompressionPreset::decl(&config),
        OutputMode::decl(&config),
        MetadataPolicy::decl(&config),
        TaskStatus::decl(&config),
        BatchStartStatus::decl(&config),
        InputItem::decl(&config),
        ScanRequest::decl(&config),
        ScanEvent::decl(&config),
        PreviewRequest::decl(&config),
        PreviewResult::decl(&config),
        BatchRequest::decl(&config),
        BatchStartResult::decl(&config),
        ItemProgress::decl(&config),
        BatchSummary::decl(&config),
        FormatCapability::decl(&config),
        InputLimits::decl(&config),
        AppCapabilities::decl(&config),
    ];
    let declarations = declarations.map(|declaration| format!("export {declaration}"));
    let error_codes =
        serde_json::to_string(ErrorCode::ALL).expect("failed to serialize error codes");
    let content = format!(
        "// This file is generated by `npm run ipc:generate`. Do not edit.\n\n{}\n\nexport const ERROR_CODES = {error_codes} as const;\n",
        declarations.join("\n\n"),
    );
    if check {
        let existing = fs::read_to_string(&output).expect("generated IPC bindings are missing");
        if existing != content {
            panic!("generated IPC bindings are out of date; run `npm run ipc:generate`");
        }
    } else {
        if let Some(parent) = output.parent() {
            fs::create_dir_all(parent).expect("failed to create binding directory");
        }
        fs::write(output, content).expect("failed to write IPC bindings");
    }
}
